Changes docker setup to work with heroku.

diff --git a/bin/dev-entrypoint b/bin/dev-entrypoint
--- a/bin/dev-entrypoint
+++ b/bin/dev-entrypoint
@@ -1,8 +1,17 @@
 #!/bin/bash
 set -e
-umask 0000
-# Remove potentially pre-existing server.pid to avoid 'Rails server already running' issues.
+
+# Remove a potentially pre-existing server.pid for Rails.
 rm -f /app/tmp/pids/server.pid
 
-# Execute main process
+bundle exec rake db:migrate
+
+if [[ $? != 0 ]]; then
+  echo
+  echo "== Failed to migrate. Running setup first."
+  echo
+  bundle exec rake db:setup
+fi
+
+# Then exec the container's main process (what's set as CMD in the Dockerfile).
 exec "$@"
